name-template: v$NEXT_PATCH_VERSION
#tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: bug
  - title: 🧰 Feature Flags
    label: feature-flag
tag-template: $TITLE @$AUTHOR (#$NUMBER)
template: |
  $CHANGES
